### ISSUE TITLE
How to extract feature loading？

### ISSUE THREAD

**Issue by wanglu2014** [neurostatslab/tensortools#36]
How to extract feature loading after tensor decomposition， just like PCA？
Thank you for your help！

**Comment by ahwillia** [comment]
First fit the decomposition:

```python
decomp = tt.cp_als(X, rank=R, verbose=True)        # For regular CP decomposition 
decomp = tt.ncp_bcd(X, rank=R, verbose=True)    # For nonnegative CP
```

Then, extract the factor matrices like `decomp.factors[0]`, `decomp.factors[1]`, etc.
